#include <stddef.h>

#ifndef CRAWLER_ERROR_H_
#define CRAWLER_ERROR_H_

typedef enum {
    CRAWLER_ERROR_ABRUPT_CLOSING_OF_EMPTY_COMMENT,
    CRAWLER_ERROR_ABRUPT_DOCTYPE_PUBLIC_IDENTIFIER,
    CRAWLER_ERROR_ABRUPT_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_ERROR_ABSENCE_OF_DIGITS_IN_NUMERIC_CHARACTER_REFERENCE,
    CRAWLER_ERROR_CDATA_IN_HTML_CONTENT,
    CRAWLER_ERROR_CHARACTER_REFERENCE_OUTSIDE_UNICODE_RANGE,
    CRAWLER_ERROR_CONTROL_CHARACTER_IN_INPUT_STREAM,
    CRAWLER_ERROR_CONTROL_CHARACTER_REFERENCE,
    CRAWLER_ERROR_DISALLOWED_PROCESSING_INSTRUCTION_TARGET,
    CRAWLER_ERROR_DUPLICATE_ATTRIBUTE,
    CRAWLER_ERROR_END_TAG_WITH_ATTRIBUTES,
    CRAWLER_ERROR_END_TAG_WITH_TRAILING_SOLIDUS,
    CRAWLER_ERROR_EOF_BEFORE_TAG_NAME,
    CRAWLER_ERROR_EOF_IN_CDATA,
    CRAWLER_ERROR_EOF_IN_COMMENT,
    CRAWLER_ERROR_EOF_IN_DOCTYPE,
    CRAWLER_ERROR_EOF_IN_PROCESSING_INSTRUCTION,
    CRAWLER_ERROR_EOF_IN_SCRIPT_HTML_COMMENT_LIKE_TEXT,
    CRAWLER_ERROR_EOF_IN_TAG,
    CRAWLER_ERROR_INCORRECTLY_CLOSED_COMMENT,
    CRAWLER_ERROR_INCORRECTLY_OPENED_COMMENT,
    CRAWLER_ERROR_INVALID_CHARACTER_SEQUENCE_AFTER_DOCTYPE_NAME,
    CRAWLER_ERROR_INVALID_FIRST_CHARACTER_OF_PROCESSING_INSTRUCTION_TARGET,
    CRAWLER_ERROR_INVALID_FIRST_CHARACTER_OF_TAG_NAME,
    CRAWLER_ERROR_INVALID_PROCESSING_INSTRUCTION_TARGET,
    CRAWLER_ERROR_MISSING_ATTRIBUTE_VALUE,
    CRAWLER_ERROR_MISSING_DOCTYPE_NAME,
    CRAWLER_ERROR_MISSING_DOCTYPE_PUBLIC_IDENTIFIER,
    CRAWLER_ERROR_MISSING_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_ERROR_MISSING_END_TAG_NAME,
    CRAWLER_ERROR_MISSING_QUOTE_BEFORE_DOCTYPE_PUBLIC_IDENTIFIER,
    CRAWLER_ERROR_MISSING_QUOTE_BEFORE_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_ERROR_MISSING_SEMICOLON_AFTER_CHARACTER_REFERENCE,
    CRAWLER_ERROR_MISSING_WHITESPACE_AFTER_DOCTYPE_PUBLIC_KEYWORD,
    CRAWLER_ERROR_MISSING_WHITESPACE_AFTER_DOCTYPE_SYSTEM_KEYWORD,
    CRAWLER_ERROR_MISSING_WHITESPACE_BEFORE_DOCTYPE_NAME,
    CRAWLER_ERROR_MISSING_WHITESPACE_BETWEEN_ATTRIBUTES,
    CRAWLER_ERROR_MISSING_WHITESPACE_BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS,
    CRAWLER_ERROR_NESTED_COMMENT,
    CRAWLER_ERROR_NONCHARACTER_CHARACTER_REFERENCE,
    CRAWLER_ERROR_NONCHARACTER_IN_INPUT_STREAM,
    CRAWLER_ERROR_NON_VOID_HTML_ELEMENT_START_TAG_WITH_TRAILING_SOLIDUS,
    CRAWLER_ERROR_NULL_CHARACTER_REFERENCE,
    CRAWLER_ERROR_SURROGATE_CHARACTER_REFERENCE,
    CRAWLER_ERROR_SURROGATE_IN_INPUT_STREAM,
    CRAWLER_ERROR_UNEXPECTED_CHARACTER_AFTER_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_ERROR_UNEXPECTED_CHARACTER_IN_ATTRIBUTE_NAME,
    CRAWLER_ERROR_UNEXPECTED_CHARACTER_IN_UNQUOTED_ATTRIBUTE_VALUE,
    CRAWLER_ERROR_UNEXPECTED_EQUALS_SIGN_BEFORE_ATTRIBUTE_NAME,
    CRAWLER_ERROR_UNEXPECTED_NULL_CHARACTER,
    CRAWLER_ERROR_UNEXPECTED_SOLIDUS_IN_TAG,
    CRAWLER_ERROR_UNKNOWN_NAMED_CHARACTER_REFERENCE
} CrawlerParseErrorType;

typedef struct {
    size_t buffer_offset;
    int code_point;
    CrawlerParseErrorType type;
} CrawlerParseError;

#endif