#ifndef CRAWLER_LEXER_H_
#define CRAWLER_LEXER_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "string_buffer.h"

typedef enum {
    CRAWLER_LEXER_ERROR,
    CRAWLER_LEXER_SUCCESS,
    CRAWLER_LEXER_NEXT_CP,
    CRAWLER_LEXER_MISSING_CP
} CrawlerLexerResult;

typedef enum {
    CRAWLER_LEXER_STATE_DATA,
    CRAWLER_LEXER_STATE_RCDATA,
    CRAWLER_LEXER_STATE_RAWTEXT,
    CRAWLER_LEXER_STATE_SCRIPT_DATA,
    CRAWLER_LEXER_STATE_PLAINTEXT,
    CRAWLER_LEXER_STATE_TAG_OPEN,
    CRAWLER_LEXER_STATE_END_TAG_OPEN,
    CRAWLER_LEXER_STATE_TAG_NAME,
    CRAWLER_LEXER_STATE_RCDATA_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_RCDATA_END_TAG_OPEN,
    CRAWLER_LEXER_STATE_RCDATA_END_TAG_NAME,
    CRAWLER_LEXER_STATE_RAWTEXT_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_RAWTEXT_END_TAG_OPEN,
    CRAWLER_LEXER_STATE_RAWTEXT_END_TAG_NAME,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_END_TAG_OPEN,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_END_TAG_NAME,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPE_START,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPE_START_DASH,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED_DASH,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED_DASH_DASH,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED_END_TAG_OPEN,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_ESCAPED_END_TAG_NAME,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPE_START,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPED,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPED_DASH,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_SCRIPT_DATA_DOUBLE_ESCAPE_END,
    CRAWLER_LEXER_STATE_BEFORE_ATTRIBUTE_NAME,
    CRAWLER_LEXER_STATE_ATTRIBUTE_NAME,
    CRAWLER_LEXER_STATE_AFTER_ATTRIBUTE_NAME,
    CRAWLER_LEXER_STATE_BEFORE_ATTRIBUTE_VALUE,
    CRAWLER_LEXER_STATE_ATTRIBUTE_VALUE_DOUBLE_QUOTED,
    CRAWLER_LEXER_STATE_ATTRIBUTE_VALUE_SINGLE_QUOTED,
    CRAWLER_LEXER_STATE_ATTRIBUTE_VALUE_UNQUOTED,
    CRAWLER_LEXER_STATE_AFTER_ATTRIBUTE_VALUE_QUOTED,
    CRAWLER_LEXER_STATE_SELF_CLOSING_START_TAG,
    CRAWLER_LEXER_STATE_BOGUS_COMMENT,
    CRAWLER_LEXER_STATE_MARKUP_DECLARATION_OPEN,
    CRAWLER_LEXER_STATE_COMMENT_START,
    CRAWLER_LEXER_STATE_COMMENT_START_DASH,
    CRAWLER_LEXER_STATE_COMMENT,
    CRAWLER_LEXER_STATE_COMMENT_LESS_THAN_SIGN,
    CRAWLER_LEXER_STATE_COMMENT_LESS_THAN_SIGN_BANG,
    CRAWLER_LEXER_STATE_COMMENT_LESS_THAN_SIGN_BANG_DASH,
    CRAWLER_LEXER_STATE_COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH,
    CRAWLER_LEXER_STATE_COMMENT_END_DASH,
    CRAWLER_LEXER_STATE_COMMENT_END,
    CRAWLER_LEXER_STATE_COMMENT_END_BANG,
    CRAWLER_LEXER_STATE_DOCTYPE,
    CRAWLER_LEXER_STATE_BEFORE_DOCTYPE_NAME,
    CRAWLER_LEXER_STATE_DOCTYPE_NAME,
    CRAWLER_LEXER_STATE_AFTER_DOCTYPE_NAME,
    CRAWLER_LEXER_STATE_AFTER_DOCTYPE_PUBLIC_KEYWORD,
    CRAWLER_LEXER_STATE_BEFORE_DOCTYPE_PUBLIC_IDENTIFIER,
    CRAWLER_LEXER_STATE_DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED,
    CRAWLER_LEXER_STATE_DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED,
    CRAWLER_LEXER_STATE_AFTER_DOCTYPE_PUBLIC_IDENTIFIER,
    CRAWLER_LEXER_STATE_BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS,
    CRAWLER_LEXER_STATE_AFTER_DOCTYPE_SYSTEM_KEYWORD,
    CRAWLER_LEXER_STATE_BEFORE_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_LEXER_STATE_DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED,
    CRAWLER_LEXER_STATE_DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED,
    CRAWLER_LEXER_STATE_AFTER_DOCTYPE_SYSTEM_IDENTIFIER,
    CRAWLER_LEXER_STATE_BOGUS_DOCTYPE_STATE,
    CRAWLER_LEXER_STATE_CDATA_SECTION,
    CRAWLER_LEXER_STATE_CDATA_SECTION_BRACKET,
    CRAWLER_LEXER_STATE_CDATA_SECTION_END,
    CRAWLER_LEXER_STATE_PROCESSING_INSTRUCTION_OPEN,
    CRAWLER_LEXER_STATE_PROCESSING_INSTRUCTION_TARGET,
    CRAWLER_LEXER_STATE_AFTER_PROCESSING_INSTRUCTION_TARGET,
    CRAWLER_LEXER_STATE_PROCESSING_INSTRUCTION_DATA,
    CRAWLER_LEXER_STATE_PROCESSING_INSTRUCTION_QUESTIONABLE,
    CRAWLER_LEXER_STATE_CHARACTER_REFERENCE,
    CRAWLER_LEXER_STATE_NAMED_CHARACTER_REFERENCE,
    CRAWLER_LEXER_STATE_AMBIGUOUS_AMPERSAND,
    CRAWLER_LEXER_STATE_NUMERIC_CHARACTER_REFERENCE,
    CRAWLER_LEXER_STATE_HEXADECIMAL_CHARACTER_REFERENCE_START,
    CRAWLER_LEXER_STATE_HEXADECIMAL_CHARACTER_REFERENCE,
    CRAWLER_LEXER_STATE_DECIMAL_CHARACTER_REFERENCE,
    CRAWLER_LEXER_STATE_NUMERIC_CHARACTER_REFERENCE_END
} CrawlerLexerState;

typedef enum {
    CRAWLER_IM_INITIAL,
    CRAWLER_IM_BEFORE_HTML,
    CRAWLER_IM_BEFORE_HEAD,
    CRAWLER_IM_IN_HEAD,
    CRAWLER_IM_IN_HEAD_NOSCRIPT,
    CRAWLER_IM_AFTER_HEAD,
    CRAWLER_IM_IN_BODY,
    CRAWLER_IM_TEXT,
    CRAWLER_IM_IN_TABLE,
    CRAWLER_IM_IN_TABLE_TEXT,
    CRAWLER_IM_IN_CAPTION,
    CRAWLER_IM_IN_COLUMN_GROUP,
    CRAWLER_IM_IN_TABLE_BODY,
    CRAWLER_IM_IN_ROW,
    CRAWLER_IM_IN_CELL,
    CRAWLER_IM_IN_TEMPLATE,
    CRAWLER_IM_AFTER_BODY,
    CRAWLER_IM_IN_FRAMESET,
    CRAWLER_IM_AFTER_FRAMESET,
    CRAWLER_IM_AFTER_AFTER_BODY,
    CRAWLER_IM_AFTER_AFTER_FRAMESET 
} CrawlerInsertionMode;

typedef enum {
    CRAWLER_SM_NORMAL,
    CRAWLER_SM_DISABLED,
    CRAWLER_SM_INER,
    CRAWLER_SM_FRAGMENT
} CrawlerParserScriptingMode;

typedef struct CrawlerInternalLexerContext {
    CrawlerLexerState current_state;
    CrawlerLexerState return_state;

    CrawlerString temporary_buffer;

    bool start_tag_emitted;
    CrawlerString last_emitted_start_tag_name;

    struct CrawlerInternalAttributeNode* current_attribute_node;

    /* The type is unclear. */
    // int character_reference_code;
} CrawlerLexerContext;

void crawler_lexer_init(CrawlerLexerContext* lexer);

struct CrawlerInternalParserContext;
CrawlerLexerResult crawler_lexer_gen_token(struct CrawlerInternalParserContext* parser);

#ifdef __cplusplus
}
#endif
#endif // CRAWLER_LEXER_H_