#ifndef CRAWLER_INSERTION_MODE_H_
#define CRAWLER_INSERTION_MODE_H_

typedef enum {
    CRAWLER_IM_INITIAL,
    CRAWLER_IM_BEFORE_HTML,
    CRAWLER_IM_BEFORE_HEAD,
    CRAWLER_IM_IN_HEAD,
    CRAWLER_IM_IN_HEAD_NOSCRIPT,
    CRAWLER_IM_AFTER_HEAD,
    CRAWLER_IM_IN_BODY,
    CRAWLER_IM_TEXT,
    CRAWLER_IM_IN_TABLE,
    CRAWLER_IM_IN_TABLE_TEXT,
    CRAWLER_IM_IN_CAPTION,
    CRAWLER_IM_IN_COLUMN_GROUP,
    CRAWLER_IM_IN_TABLE_BODY,
    CRAWLER_IM_IN_ROW,
    CRAWLER_IM_IN_CELL,
    CRAWLER_IM_IN_TEMPLATE,
    CRAWLER_IM_AFTER_BODY,
    CRAWLER_IM_IN_FRAMESET,
    CRAWLER_IM_AFTER_FRAMESET,
    CRAWLER_IM_AFTER_AFTER_BODY,
    CRAWLER_IM_AFTER_AFTER_FRAMESET 
} CrawlerInsertionModeType;

#endif