#ifndef CRAWLER_TOKEN_H_
#define CRAWLER_TOKEN_H_

typedef enum {
    CRAWLER_TOKEN_CHARACTER,
    CRAWLER_TOKEN_EOF,
    CRAWLER_TOKEN_START_TAG,
    CRAWLER_TOKEN_END_TAG,
    CRAWLER_TOKEN_COMMENT,
    CRAWLER_TOKEN_TAG,
    CRAWLER_TOKEN_DOCTYPE,
    CRAWLER_TOKEN_PROCESSING_INSTRUCTION
} CrawlerTokenType;

#endif // CRAWLER_TOKEN_H_